### ISSUE TITLE
JSON/YAML schema null support

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#122]
Many of the JSON/YAML schema properties have a single type ([example](https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/recordGeoJSON.yaml#L40-L43)).

When doing validation testing against a sample instance document with, say, `"title": null`, the JSON schema validator throws error.  If I update `core/openapi/schemas/recordGeoJSON.yaml` (`properties.title`) to allow nulls, i.e.:

```yaml
title:
  type:
    - string
    - null
  description: |-
    A human-readable name given to the resource.
```

The JSON instance document then validates fine.

What is the general guidance on nullable properties?

cc @pvretano @cportele
