### ISSUE TITLE
https://rawgit.com/opengeospatial/CAT4.0/master/docs/18-065.html no longer available

### ISSUE THREAD

**Issue by KoalaGeo** [opengeospatial/ogcapi-records#18]
https://rawgit.com/opengeospatial/CAT4.0/master/docs/18-065.html no longer available

**Comment by jyutzler** [comment]
We are pretty sure 18-065 is obsolete, but we are going to turn https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/20-004.adoc into something with a permalink so that it would be accessible through a similar URL.

**Comment by jyutzler** [comment]
As an aside, if GitHub were able to resolve https://github.com/github/markup/issues/1095, this would be less of an issue for us.

**Comment by KoalaGeo** [comment]
As an aside, if you moved to rst instead of adoc that would work with current infrastructure. 

example documentation : https://github.com/BritishGeologicalSurvey/Groundhog 

This documentation is written in ReStructured Text hosted on GitHub pages, built using Sphinx via Gitub Actions each time theres a commit to the master. https://britishgeologicalsurvey.github.io/Groundhog/#documenting-the-documentation

**Comment by jyutzler** [comment]
AsciiDoc can also be rendered through GitHub.io, but that requires someone to set up the pipeline. Direct rendering of AsciiDoc (including "includes", as requested in that other ticket) would obviate that need.

**Comment by tomkralidis** [comment]
I think AsciiDoc is the OGC standard for writing up the standards.  To echo @jyutzler, we'll follow the OGC workflow for publishing the AsciiDoc accordingly.

**Comment by tomkralidis** [comment]
@pvretano I think you mentioned discussing this with OGC?

We could also setup a GitHub workflow (saving the below to `.github/workflows/main.yml`) like (untested):

```yaml
name: CI

on: [ push , pull_request ]

jobs:
  make_xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}
    - name: install asciidoctor dependencies
      run: |
        gem install asciidoctor --pre
        gem install asciidoctor-pdf --pre
    - name: create standard document in HTML and PDF
      run: | 
        cd core/standard
        asciidoctor --trace -o 20-004.html 20-004.adoc
        asciidoctor -r asciidoctor-pdf --trace -b pdf -o 20-004.pdf 20-004.adoc
        git commit -m "re-publish draft" *.pdf *.html
        git push
```
