### ISSUE TITLE
clarify contact name/organization

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-records#294]
The [current contact schema](https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/contact.yaml) describes contact `name` / `organization` as follows:

```yaml
  name:
    type: string
    description: |-
      The name of the organization or the individual.
  organization:
    type: string
    description:
      Organization/affiliation of the individual/responsible person. In
      case of an organization, the name property should be used and this
      property is not to be used.
```

`name` is a required property.

Is implementing `name` or `organization`, then, domain/activity specific?  For example, consider a catalogue implementing facets on contact organizations.  Would the catalogue have to check if `organization` exists?  If not, then use `name` and assume `name` is an organization?

Should we consider a contact to require ~ONE OF~ ANY OF `name` or `organization`, with clear definitions of each?

cc @pvretano @kalxas @m-mohr @pvgenuchten
