### ISSUE TITLE
STAC alignment for sortby

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-records#380]
See https://github.com/opengeospatial/ogcapi-processes/issues/429#issuecomment-2242747022.

The schema of the `defaultSortOrder` should be aligned with what STAC uses.

**Comment by pvretano** [comment]
STAC defines the sortBy parameter as:
````
name: sortby
in: query
description: |-
        **Extension:** Sort

        An array of property names, prefixed by either "+" for ascending or
        "-" for descending. If no prefix is provided, "+" is assumed.
required: false
schema:
  type: string
  example: '+id,-properties.eo:cloud_cover'
style: form
explode: false
````

OARec defines the sortBy parameter as:
````
name: sortby
in: query
description: |-
  Specifies a comma-separated list of property names by which the response shall
  be sorted.  If the property name is preceded by a plus (+) sign it indicates
  an ascending sort for that property.  If the property name is preceded by a
  minus (-) sign it indicates a descending sort for that property.  If the
  property is not preceded by a plus or minus, then the default sort order
  implied is ascending (+).
required: false
schema:
  type: array
  minItems: 1
  items:
    type: string
    pattern: '[+|-]?[A-Za-z_].*'
explode: false
style: form
````

These seem equivalent except for the use of pattern in OARec.  We should either remove that or loosen it up a little ... perhaps `[+|-]?.*`.
