### ISSUE TITLE
Example "Records Example in GeoJSON" appears to have invalid `formats`

### ISSUE THREAD

**Issue by davidblasby** [opengeospatial/ogcapi-records#403]
Please let me know if I am putting this issue in the correct place.

In section 8.5.5.4 of the OGCAPI-Records spec, the GeoJSON look like this:

```
  {
  ...
 "properties": {
      ...
      "formats": [
            "CSV",
            "GeoJSON"
          ],
    ...
 }
```

However, the definition of Formats is (via `recordGeoJSON` -> `recordCommonProperties.yaml` -> `format.yaml`):

```
---
type: object
anyOf:
- required:
  - name
- required:
  - mediaType
properties:
  name:
    type: string
  mediaType:
    type: string
```

The example is using a `List<String>`, while the definition shows a `List<Object>`.

I think the example should be more like this (see section 8.2.9):

```
    ...
    "formats": [
        { "name": "TK50" },
        { "name": "GRIB", "mediaType": "application/x-grib" },
        { "mediaType": "application/zip"}
    ]
    ...
```
