### ISSUE TITLE
time parameter

### ISSUE THREAD

**Issue by mhogeweg** [opengeospatial/ogcapi-records#54]
working on implementing the draft spec, I run into the specification of the time parameter as used in /collections and /collections/:collectonId/items.

currently time is defined as follows:
```
        - name: time
          in: query
          description:  Either a date-time or a period string that adheres to RFC 3339. Examples:
            * A date-time: "2018-02-12T23:20:50Z" 
            * A period: "2018-02-12T00:00:00Z/2018-03-18T12:31:12Z" or "2018-02-12T00:00:00Z/P1M6DT12H31M12S"
            Only collections that have a temporal property that intersects the value of `time` are selected.
            If a collection has multiple temporal properties, it is the decision of the server whether only a single temporal property is used to determine the extent or all relevant temporal properties.
          required: false
          style: form
          explode: false
          schema:
            type: string
```

Can we consider breaking this apart into from/to parameters? that way the yaml can be a lot more specific using the ```format: date-time``` modifier of the string type. 

```
        - name: from
          in: query
          description: date time according to RFC 3339, section 5.6. Example 2018-02-12T23:20:50Z
          required: false
          schema:
            type: string  
            format: date-time
        - name: to
          in: query
          description: date time according to RFC 3339, section 5.6. Examples "2018-02-12T23:20:50Z"
          required: false
          schema:
            type: string  
            format: date-time
```
